version: '3.8'

services:
  # Caché principal y almacenamiento de sesiones
  redis:
    image: redis:7-alpine
    container_name: erp_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Base de datos documental para el fallback de sesiones
  mongo:
    image: mongo:7
    container_name: erp_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    restart: unless-stopped